# first import the pakage at the top

In [5]:
import numpy as np

In [20]:
print(np.__version__)

1.21.5


In [21]:
arr = np.array(42) # 0D Array

display(arr) 

array(42)

In [9]:
a = np.array([1,2,3,4]) #1D Array

In [7]:
display(a)

array([1, 2, 3, 4])

In [10]:
b = np.array([[1,2,3],[4,5,6]]) #2D Array 

In [11]:
display(b)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a.ndim

1

In [15]:
b.ndim

2

In [17]:
a + 1  # Add 1 in a Mean +1 in all the element of an array 

array([2, 3, 4, 5])

In [18]:
b + 2 # Add 2 in a Mean +2 in all the element of an array

array([[3, 4, 5],
       [6, 7, 8]])

In [19]:
a = np.arange(2*2).reshape(2,2)
display(a)

array([[0, 1],
       [2, 3]])

In [22]:
c = np.arange(3*3*3).reshape(3,3,3)

In [23]:
display(c)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [36]:
d = np.arange(3*3*2).reshape(2,3,3)

In [37]:
display(d)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])